# ===================================================================
# Spring Boot configuration for the "awsses" profile.
#
# This configuration overrides the application.yml file.
#
# This is configuration for the Agency04 AWS Simple Email Service (SeS)
# ===================================================================

spring:
  mail:
    host: email-smtp.eu-west-1.amazonaws.com
    username: ${EMAIL_USER}
    password: ${EMAIL_PWD}
    protocol: smtps
    port: 465
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          port: 465
          auth: true
        smtp:
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
