# ===================================================================
# Spring Boot configuration for the "awsses" profile.
#
# This is configuration for the AWS Simple Email Service (SeS)
# ===================================================================

spring:
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USER}
    password: ${MAIL_PWD}
    protocol: smtps
    port: 465
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          port: 465
          auth: true
        smtp:
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
